# Generated by Django 6.0.1 on 2026-04-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
