# Generated by Django 6.0.4 on 2026-04-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_workout_step_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='category',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength'), ('flexibility', 'Flexibility'), ('hiit', 'HIIT'), ('squats', 'Squats'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
