# Generated by Django 6.0.4 on 2026-04-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_alter_workout_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='video_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
